"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  zh: {
    "nav.home": "首页",
    "nav.research": "研究",
    "nav.teaching": "教学",
    "nav.cv": "简历",
    "nav.blog": "博客",
    "nav.contact": "联系",
    "profile.title": "个人简介",
    "profile.name": "莫雯茹",
    "profile.position": "国际贸易助理教授",
    "profile.intro1": "我是一名国际贸易助理教授，专注于经济学、战略管理和跨文化研究。",
    "profile.intro2": "我的研究重点是区域贸易竞争力、农业商品市场动态和生猪产业经济学。",
    "profile.intro3": "在这个网站上，我展示了我的学术成果，并撰写关于我感兴趣的经济学和商业相关话题。",
    "profile.group": "经济与管理学院",
    "profile.school": "湛江科技学院",
    "research.title": "研究领域",
    "research.item1": "国际贸易与区域经济合作",
    "research.item2": "农业经济与产业组织",
    "research.item3": "全球商品市场与贸易政策",
    "research.item4": "女性与劳动力市场研究",
    "research.item5": "农村振兴与可持续发展",
    "research.overview": "概述",
    "research.overview.desc1": "在国际贸易与区域经济合作领域，我的研究侧重于RCEP等贸易协定对区域贸易竞争力、农产品市场动态及生猪产业经济的影响，旨在为产业升级和政策制定提供实证依据。",
    "research.overview.desc2": "在农业经济与产业组织方向，我深入分析茶叶、机电产品等出口贸易中的结构性问题和非关税壁垒，并提出针对性解决方案。",
    "research.overview.desc3": "全球商品市场与贸易政策是我关注的重点之一，特别是猪肉等农产品的供需变化、价格波动及其政策影响。",
    "research.overview.desc4": "我还致力于女性与劳动力市场研究，分析性别规范、制度障碍和人际网络对女性职业发展的影响。",
    "research.overview.desc5": "在农村振兴与可持续发展方面，我参与了电商课程改革和生猪产业的链条整合研究，以促进小农户的可持续发展和地方经济转型。",
    "research.experience.1.title": "RCEP框架下广东省机电产品对日出口现状研究",
    "research.experience.1.duration": "2024年9月 - 2025年5月",
    "research.experience.1.focus": "研究RCEP对区域贸易竞争力的影响；机电产品出口的实证分析（市场份额，比较优势）；产业升级的政策建议。",
    "research.experience.1.responsibilities": "作为指导老师：指导使用MS、TC、RCA指数进行定量分析；监督数据收集（中国海关，联合国商品贸易统计数据库）；就理论框架（波特价值链，贸易竞争力理论）提供建议。",
    "research.experience.1.findings": "关键发现：RCEP提升了广东省市场份额（MS指数↑5.75%），但技术壁垒限制了贸易竞争力（TC指数仍为负）；出口以低附加值产品为主（80%机械），需创新和品牌建设；建议双重策略：技术标准化（JIS/PSE）和品牌差异化。",
    "research.experience.2.title": "浙江省茶叶出口问题与对策研究",
    "research.experience.2.duration": "2024年9月 - 2025年5月",
    "research.experience.2.focus": "研究RCEP对区域农产品贸易竞争力的影响；茶叶出口效率的实证分析（市场份额，价值链）；克服非关税壁垒的政策建议。",
    "research.experience.2.responsibilities": "作为指导老师：指导使用赫克歇尔-俄林模型（H-O模型）和贸易指数（RCA/MS）进行定量分析；监督数据收集（中国海关，联合国商品贸易统计数据库，省级统计年鉴）；就比较优势理论在茶叶出口结构优化中的应用提供建议。",
    "research.experience.2.findings": "关键发现：浙江茶叶出口以低附加值绿茶为主（96%），与全球红茶需求不符；RCA指数&gt;1.25证实比较优势，但MS指数下降（2015年52亿美元→2023年46亿美元）；非关税壁垒（欧盟农药标准）使合规成本增加约30%。",
    "research.experience.3.title": "江苏省机电产品出口贸易问题与对策研究",
    "research.experience.3.duration": "2024年9月 - 2025年5月",
    "research.experience.3.focus": "分析江苏省机电产品出口的结构性挑战（如低附加值主导）和贸易壁垒，并提出增强竞争力的策略。",
    "research.experience.3.responsibilities": "作为指导老师：指导数据收集/分析（南京海关记录2013-2024年）和比较市场研究；监督方法论设计（定量回归+案例研究）和政策建议的制定。",
    "research.experience.3.findings": "关键发现：高科技出口占比达46.7%，但面临低利润瓶颈；贸易壁垒（如RoHS）使合规成本增加8-12%。",
    "research.experience.4.title": "湛江科技学院生猪产业经济研究所研究员",
    "research.experience.4.duration": "2024年9月 - 至今",
    "research.experience.4.focus": "全球猪肉市场动态（供需变化，价格波动）；农产品市场动态（小麦，玉米，豆粕）；生猪产业链垂直整合效率；基因资源保护与小农户可持续发展的政策影响分析。",
    "research.experience.4.responsibilities": "作为研究员：数据收集与分析：收集并验证USDA、FAO和国家统计年鉴的全球生产/消费数据（2019-2025）；使用10+指标（如饲料成本，母猪存栏）进行24个省份的月度价格趋势分析；田野调查：调查15家生猪企业（如牧原，温氏）；访谈120+小农户了解成本结构。政策报告与市场分析：撰写月度市场报告（广东省生猪市场报告），内容包括：价格-产量趋势预测（饲料成本，母猪存栏，屠宰量），农产品市场动态（玉米和大豆），非洲猪瘟疫情和价格波动风险评估，小农户补贴和品种保护政策建议。",
    "research.experience.4.outputs": "产出：8份被广东省农业农村厅采纳的政策报告（如《广东省生猪市场报告》（2025年1-5期），《广东省畜牧业简报》（2025年2-5期））；3篇关于生猪产业经济的出版物。",
    "research.experience.5.title": "女性在基层政府中发挥作用的障碍：中国基层公务员问卷调查案例",
    "research.experience.5.duration": "2022年4月 - 2022年9月",
    "research.experience.5.supervisor": "导师：Dr Ash Kayte Stokoe, 伯明翰大学",
    "research.experience.5.focus": "应用劳动经济学框架量化政治劳动力市场中的性别差异；通过组织经济学视角审视制度效率低下；使用网络分析指标衡量社会资本回报。",
    "research.experience.5.responsibilities": "设计混合方法研究，结合劳动经济学框架分析：采用混合方法研究，包括非定量问卷调查和定性试点研究；使用人力资本理论衡量政治参与的机会成本；通过性别化的组织经济学视角审视制度障碍；将“关系”网络作为具有不同性别回报的社会资本。",
    "research.experience.5.findings": "关键发现：性别规范和不足的照护基础设施阻碍女性职业发展；父权制“关系”文化负面影响女性公务员的发展。",
    "research.experience.6.title": "纺织行业女性工人数量的增加是否导致赋权或剥削的加剧？",
    "research.experience.6.duration": "2021年12月 - 2022年1月",
    "research.experience.6.objectives": "目标：考察女性参与纺织行业增加对赋权与剥削的影响，考虑工作条件、工资、职业发展和社会地位。",
    "research.experience.6.responsibilities": "职责：进行文献综述，分析经济参与对女性自主权的影响，并综合发展中国家女性在纺织行业就业的数据。",
    "research.experience.6.findings1": "关键发现：纺织厂女工获得增强的社交技能和决策能力，但缺乏劳动法知识阻碍了对剥削的抵抗。",
    "research.experience.6.findings2": "纺织行业提供赋权，但需要关注消除剥削以实现可持续发展。",
    "research.experience.7.title": "2019年大选保守党支持者的驱动因素",
    "research.experience.7.duration": "2022年4月 - 2022年5月",
    "research.experience.7.objectives": "目标：分析影响2019年英国大选保守党支持的因素。",
    "research.experience.7.responsibilities": "职责：提出关于脱欧情绪、住房拥有率和退休人口结构等的假设；进行统计分析并评估回归模型的拟合度和系数显著性。",
    "research.experience.7.findings": "关键发现：支持脱欧的公民、房主和老年人更倾向于支持保守党。",

    "project.title1": "高性能流体动力学模拟",
    "project.duration1": "2021 - 2024",
    "project.desc1": "开发高性能流体动力学模拟软件，支持大规模并行计算和复杂几何建模。",
    "project.title2": "自适应网格细化",
    "project.duration2": "2019 - 2022",
    "project.desc2": "研究自适应网格细化技术，提高计算精度和效率，适用于多尺度问题。",

    "collaboration.tsinghua": "清华大学",
    "collaboration.cas": "中科院计算所",
    "collaboration.mit": "MIT",
    "collaboration.huawei": "华为研究院",

    "funding.nsfc.title": "国家自然科学基金",
    "funding.nsfc.duration": "2022 - 2025",
    "funding.nsfc.desc": "高性能计算与多物理场耦合模拟研究",
    "funding.most.title": "科技部重点研发计划",
    "funding.most.duration": "2020 - 2023",
    "funding.most.desc": "新一代高性能计算框架开发与应用",

    "impact.sci_papers": "发表SCI论文",
    "impact.citations": "引用次数",
    "impact.international_projects": "国际合作项目",
    "education.title": "教育背景",
    "publications.title": "发表成果",
    "publications.filter": "筛选",
    "publications.year": "年份",
    "publications.type": "类型",
    "publications.field": "领域",
    "teaching.title": "教学经历",
    "contact.title": "联系方式",
    "footer.copyright": "版权所有",
    "language.toggle": "切换语言",
    "research.timeline": "时间轴",
    "research.projects": "项目",
    "research.collaborations": "合作",
    "research.funding": "资助",
    "research.impact": "影响",
    "research.badge": "研究",
    "teaching.courses": "课程",
    "teaching.students": "学生",
    "teaching.resources": "教学资源",
    "contact.info": "联系信息",
    "contact.email": "电子邮件",
    "contact.email.value": "wxm201@alumni.bham.ac.uk",
    "contact.phone": "电话",
    "contact.phone.value": "+86 158-1171-3253",
    "contact.address": "地址",
    "contact.address.value": "湛江科技学院",
    "footer.about": "关于",
    "footer.about.desc": "学术个人主页，展示研究成果、教学经历和学术贡献。",
    "footer.quicklinks": "快速链接",
    "footer.resources": "学术资源",
    "footer.privacy": "隐私政策",
    "footer.terms": "使用条款",
    "cv.title": "简历",
    "cv.download.zh": "下载中文简历",
    "cv.download.en": "下载英文简历",
    "cv.personal": "个人信息",
    "cv.name": "姓名",
    "cv.position": "职位",
    "cv.institution": "机构",
    "cv.email": "邮箱",
    "cv.education": "教育背景",
    "cv.work_experience": "工作经历",
    "cv.research_experience": "研究经历",
    "cv.additional_info": "附加信息",
    "cv.languages": "语言",
    "cv.technical_skills": "技术技能",
    "cv.complete": "如需完整简历，请点击上方下载按钮或",
    "cv.contact": "联系我",
    "blog.title": "博客",
    "blog.latest": "最新文章",
    "blog.categories": "分类",
    "blog.tags": "标签",
    "blog.readmore": "阅读更多",
    "publications.journal.label": "期刊",
    "publications.conference.label": "会议",
    "publications.book.label": "书籍",
    "publications.field.labor-economics": "劳动经济学",
    "publications.field.agricultural-economics": "农业经济学",
    "publications.field.political-science": "政治学",
    "publications.1.title": "Does the Increase in Female Workers in the Textile Industry Lead to Empowerment or Increased Female Exploitation?",
    "publications.1.authors": "Mo, W.",
    "publications.1.journal": "Journal of Theory and Practice of Social Science",
    "publications.1.year": "2023",
    "publications.1.type": "journal",
    "publications.1.field": "labor-economics",
    "publications.1.doi": "2790-1513",
    "publications.1.abstract": "This paper examines the impact of increased female participation in the textile industry on empowerment versus exploitation, considering working conditions, wages, career advancement, and societal status.",
    "publications.2.title": "Barriers to Women's Gaining a Role in Grassroots Government: The Case of a Questionnaire Survey of Grassroots Civil Servants in China.",
    "publications.2.authors": "Mo, W.",
    "publications.2.journal": "Studies in Social Science & Humanities",
    "publications.2.year": "2024",
    "publications.2.type": "journal",
    "publications.2.field": "political-science",
    "publications.2.doi": "2709-7862",
    "publications.2.abstract": "This study applied labor economics frameworks to quantify gender disparities in political labor markets, examined institutional inefficiencies through an organizational economics lens, and measured social capital returns using network analysis metrics.",
    "publications.3.title": "Conservation of Indigenous Pig Breeds and Cooperative Development with Small-scale Farmers in Guangdong.",
    "publications.3.authors": "Zhang, H., Mo, W., Liang, J., et al.",
    "publications.3.journal": "Swine Industry",
    "publications.3.year": "2024",
    "publications.3.type": "journal",
    "publications.3.field": "agricultural-economics",
    "publications.3.doi": "4, 15-18",
    "publications.3.abstract": "This research focuses on the conservation of indigenous pig breeds and promoting cooperative development with small-scale farmers in Guangdong.",
    "publications.4.title": "Current status and trends in the pork consumption market.",
    "publications.4.authors": "Zhang, H., Liu, S., Mo, W., & Liu, W.",
    "publications.4.journal": "Swine Industry",
    "publications.4.year": "2024",
    "publications.4.type": "journal",
    "publications.4.field": "agricultural-economics",
    "publications.4.doi": "4, 25-30",
    "publications.4.abstract": "This paper analyzes the current status and future trends in the pork consumption market.",
    "publications.5.title": "Reflections on the construction of a full-industry-chain pig farming conglomerate.",
    "publications.5.authors": "Liu, L., Feng, X., Mo, W., & Zhang, H.",
    "publications.5.journal": "Swine Industry",
    "publications.5.year": "2024",
    "publications.5.type": "journal",
    "publications.5.field": "agricultural-economics",
    "publications.5.doi": "4, 31-35",
    "publications.5.abstract": "This article provides reflections on the construction of a full-industry-chain pig farming conglomerate.",
    "education.1.period": "2021.09-2022.12",
    "education.1.school": "伯明翰大学（英国）",
    "education.1.degree": "国际政治经济学硕士（Merit）",
    "education.1.gpa": "GPA: 63%",
    "education.1.courses": "主要课程：国际政治经济学、全球化与治理、全球环境治理、政治学研究方法",
    "education.1.paper": "课程论文：纺织行业女性工人数量增加是赋权还是剥削？全球化对女性的影响；环境NGO与企业在全球环境治理中的作用等。",
    "education.2.period": "2019.09-2020.09",
    "education.2.school": "哈德斯菲尔德大学（英国）",
    "education.2.degree": "国际商务学士（高级二等荣誉）",
    "education.2.gpa": "GPA: 68%",
    "education.2.courses": "主要课程：国际商务、战略管理、跨文化研究、环境政策、企业责任与可持续发展、工作与组织心理学",
    "education.3.period": "2016.09-2020.06",
    "education.3.school": "广州华商学院（中国广东）",
    "education.3.degree": "国际商务管理学士",
    "education.3.courses": "主要课程：计量经济学、国际金融、全球市场营销管理、技术与服务贸易",
  },
  en: {
    "nav.home": "Home",
    "nav.research": "Research",
    "nav.teaching": "Teaching",
    "nav.cv": "CV",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "profile.title": "Profile",
    "profile.name": "Wenru Mo",
    "profile.position": "Assistant Professor of International Trade",
    "profile.intro1": "I am an Assistant Professor of International Trade, specializing in economics, strategic management, and cross-cultural studies.",
    "profile.intro2": "My research focuses on regional trade competitiveness, agricultural commodity market dynamics, and swine industry economics.",
    "profile.intro3": "On this website, I present my academic achievements and write about economics and business-related topics that I find interesting.",
    "profile.group": "School of Economics and Management",
    "profile.school": "Zhanjiang University of Science and Technology",
    "research.title": "Research Interests",
    "research.item1": "International Trade and Regional Economic Cooperation",
    "research.item2": "Agricultural Economics and Industrial Organization",
    "research.item3": "Global Commodity Markets and Trade Policy",
    "research.item4": "Women and Labor Market Studies",
    "research.item5": "Rural Revitalization and Sustainable Development",
    "research.overview": "Overview",
    "research.overview.desc1": "In the field of international trade and regional economic cooperation, my research focuses on the impact of trade agreements like RCEP on regional trade competitiveness, agricultural commodity market dynamics, and swine industry economics, aiming to provide empirical basis for industrial upgrading and policy formulation.",
    "research.overview.desc2": "In the area of agricultural economics and industrial organization, I delve into structural issues and non-tariff barriers in export trade of products like tea and electromechanical goods, proposing targeted solutions.",
    "research.overview.desc3": "Global commodity markets and trade policy are among my key interests, particularly the supply-demand changes, price volatility, and policy implications for agricultural products such as pork.",
    "research.overview.desc4": "I also dedicate efforts to women and labor market studies, analyzing the impact of gender norms, institutional barriers, and social networks on women's career development.",
    "research.overview.desc5": "Regarding rural revitalization and sustainable development, I've participated in e-commerce curriculum reform and research on the vertical integration of the swine industry chain to promote smallholder sustainability and local economic transformation.",
    "research.experience.1.title": "A Study on the Existing Problems of Guangdong's Mechanical and Electrical Products Export to Japan under the RCEP Framework",
    "research.experience.1.duration": "Sep 2024 - May 2025",
    "research.experience.1.focus": "Impact of RCEP on regional trade competitiveness; Empirical analysis of electromechanical exports (market share, comparative advantage); Policy recommendations for industrial upgrading.",
    "research.experience.1.responsibilities": "As Supervisor: Guided quantitative analysis using MS, TC, and RCA indices to assess competitiveness; Supervised data collection (China Customs, UN Comtrade); Advised on theoretical frameworks (Porter's Value Chain, Trade Competitiveness Theory).",
    "research.experience.1.findings": "Key Findings: RCEP boosted Guangdong's market share (MS index &uarr;5.75%), but technical barriers limited trade competitiveness (TC index remained negative); Exports were dominated by low-value-added products (80% machinery), highlighting a need for innovation and branding; Proposed dual strategies: technology standardization (JIS/PSE) and brand differentiation.",
    "research.experience.2.title": "Study on The Problems and Countermeasures of Tea Export in Zhejiang Province",
    "research.experience.2.duration": "Sep 2024 - May 2025",
    "research.experience.2.focus": "Impact of RCEP on regional agricultural trade competitiveness; Empirical analysis of tea export efficiency (market share, value chain); Policy recommendations for overcoming non-tariff barriers.",
    "research.experience.2.responsibilities": "As Supervisor: Guided quantitative analysis using Heckscher-Ohlin (H-O) model and trade indices (RCA/MS); Supervised data collection from Chinese Customs, UN Comtrade, and provincial statistical yearbooks; Advised on comparative advantage theory application to tea export structure optimization.",
    "research.experience.2.findings": "Key Findings: Zhejiang's tea exports dominated by low-value-added green tea (96% volume), misaligned with global demand of black tea; RCA index &gt;1.25 confirmed comparative advantage, but MS index declined (5.2B USD in 2015 &rarr; 4.6B USD in 2023); Non-tariff barriers (EU pesticide standards) increased compliance costs by ~30%.",
    "research.experience.3.title": "Research on problems and countermeasures in the export trade of electromechanical products in Jiangsu Province",
    "research.experience.3.duration": "Sep 2024 - May 2025",
    "research.experience.3.focus": "Analysis of structural challenges (e.g., low-value-added dominance) and trade barriers in Jiangsu's electromechanical exports, with proposed strategies for competitiveness enhancement.",
    "research.experience.3.responsibilities": "As Supervisor: Directed data collection/analysis using Nanjing Customs records (2013-2024) and comparative market studies; Oversaw methodology design (quantitative regression + case studies) and policy recommendation development.",
    "research.experience.3.findings": "Key Findings: High-tech exports reached 46.7% but faced low-profit bottlenecks; Trade barriers (e.g., RoHS) increased compliance costs by 8-12%.",
    "research.experience.4.title": "Researcher at Swine Industry Economics Institute, Zhanjiang University of Science and Technology",
    "research.experience.4.duration": "Sep 2024 - Present",
    "research.experience.4.focus": "Global pork market dynamics (supply-demand shifts, price volatility); Agricultural commodity market dynamics (wheat, corn, soybean meal); Vertical integration efficiency in swine industry chains; Policy impact analysis on genetic resource conservation & smallholder sustainability.",
    "research.experience.4.responsibilities": "As Researcher: Data Collection & Analysis: Collected and validated global production/consumption data from USDA, FAO, and national statistical yearbooks (2019-2025); Conducted monthly price trend analysis for 24 provinces using 10+ indicators (e.g., feed costs, sow inventories); Field Research: Surveyed 15 swine enterprises (e.g., Muyuan, WH Group); Interviewed 120+ smallholders on cost structures. Policy Reporting & Market Analysis: Authored monthly market reports (Guangdong Province Swine Market Report) featuring: Price-volume trend forecasting (feed costs, sow inventories, slaughter volumes), Agricultural commodity market dynamics (corn and soybean), Risk assessment of ASF outbreaks and price volatility, Policy recommendations for smallholder subsidies and breed conservation.",
    "research.experience.4.outputs": "Outputs: 8 policy reports adopted by Agricultural and Rural Department of Guangdong Province, e.g. Guangdong Province Swine Market Report (2025 Issues 1-5), Guangdong Province Livestock Bulletin (2025 Issues 2-5); 3 publications on swine industry economics.",
    "research.experience.5.title": "Barriers to Women's Gaining a Role in Grassroots Government: The Case of A Questionnaire Survey of Grassroots Civil Servants in China",
    "research.experience.5.duration": "April 2022 - September 2022",
    "research.experience.5.supervisor": "Supervisor: Dr Ash Kayte Stokoe, University of Birmingham",
    "research.experience.5.focus": "Applied labor economics frameworks to quantify gender disparities in political labor markets; Examined institutional inefficiencies through organizational economics lens; Measured social capital returns using network analysis metrics.",
    "research.experience.5.responsibilities": "Designed mixed-methods study incorporating labor economics frameworks to analyze: Employed mixed-methods research, including a non-quantitative questionnaire and qualitative pilot studies; Opportunity costs of political participation using human capital theory; Institutional barriers through gendered organizational economics lens; \"Guanxi\" networks as social capital with differential gender returns.",
    "research.experience.5.findings": "Key Findings: Gender norms and inadequate care infrastructure hinder women's career progression; The patriarchal 'guanxi' culture negatively affects the development of female civil servants.",
    "research.experience.6.title": "Does the Increase in Female Workers in the Textile Industry Lead to Empowerment or Increased Female Exploitation?",
    "research.experience.6.duration": "December 2021 - January 2022",
    "research.experience.6.objectives": "Objectives: Examine the impact of increased female participation in the textile industry on empowerment versus exploitation, considering working conditions, wages, career advancement, and societal status.",
    "research.experience.6.responsibilities": "Responsibilities: Conducted literature reviews, analyzed economic participation's effects on women’s autonomy, and synthesized data on female employment in the textile industry in developing countries.",
    "research.experience.6.findings1": "Key Findings: Women in textile factories gain enhanced social skills and decision-making capacity, but lack of labor law knowledge hinders resistance to exploitation.",
    "research.experience.6.findings2": "The textile industry offers empowerment but requires attention to eliminate exploitation for sustainability.",
    "research.experience.7.title": "The Drivers of Conservative Party Support in the 2019 General Election",
    "research.experience.7.duration": "April 2022 - May 2022",
    "research.experience.7.objectives": "Objectives: Analyze factors influencing Conservative Party support in the 2019 UK General Election.",
    "research.experience.7.responsibilities": "Responsibilities: Formulated hypotheses on Brexit sentiment, homeownership, and retirement demographics; Conducted statistical analyses and evaluated the regression model's fit and coefficient significance.",
    "research.experience.7.findings": "Key Findings: Pro-Brexit citizens, homeowners, and older individuals are more likely to support the Conservatives.",

    "project.title1": "高性能流体动力学模拟", // placeholder, these will be replaced with actual projects
    "project.duration1": "2021 - 2024",
    "project.desc1": "开发高性能流体动力学模拟软件，支持大规模并行计算和复杂几何建模。",
    "project.title2": "自适应网格细化",
    "project.duration2": "2019 - 2022",
    "project.desc2": "研究自适应网格细化技术，提高计算精度和效率，适用于多尺度问题。",

    "collaboration.tsinghua": "清华大学",
    "collaboration.cas": "中科院计算所",
    "collaboration.mit": "MIT",
    "collaboration.huawei": "华为研究院",

    "funding.nsfc.title": "国家自然科学基金",
    "funding.nsfc.duration": "2022 - 2025",
    "funding.nsfc.desc": "高性能计算与多物理场耦合模拟研究",
    "funding.most.title": "科技部重点研发计划",
    "funding.most.duration": "2020 - 2023",
    "funding.most.desc": "新一代高性能计算框架开发与应用",

    "impact.sci_papers": "发表SCI论文",
    "impact.citations": "引用次数",
    "impact.international_projects": "国际合作项目",
    "education.title": "Education",
    "publications.title": "Publications",
    "publications.filter": "Filter",
    "publications.year": "Year",
    "publications.type": "Type",
    "publications.field": "Field",
    "teaching.title": "Teaching",
    "contact.title": "Contact",
    "footer.copyright": "Copyright",
    "language.toggle": "Toggle language",
    "research.timeline": "Timeline",
    "research.projects": "Projects",
    "research.collaborations": "Collaborations",
    "research.funding": "Funding",
    "research.impact": "Impact",
    "research.badge": "Research",
    "teaching.courses": "Courses",
    "teaching.students": "Students",
    "teaching.resources": "Resources",
    "contact.info": "Contact Information",
    "contact.email": "Email",
    "contact.email.value": "wxm201@alumni.bham.ac.uk",
    "contact.phone": "Phone",
    "contact.phone.value": "+86 158-1171-3253",
    "contact.address": "Address",
    "contact.address.value": "Zhanjiang University of Science and Technology",
    "footer.about": "About",
    "footer.about.desc": "Academic personal website showcasing research, teaching, and scholarly contributions.",
    "footer.quicklinks": "Quick Links",
    "footer.resources": "Academic Resources",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "cv.title": "Curriculum Vitae",
    "cv.download.zh": "Download Chinese CV",
    "cv.download.en": "Download English CV",
    "cv.personal": "Personal Information",
    "cv.name": "Name",
    "cv.position": "Position",
    "cv.institution": "Institution",
    "cv.email": "Email",
    "cv.education": "Education",
    "cv.work_experience": "Work Experience",
    "cv.research_experience": "Research Experience",
    "cv.additional_info": "Additional Information",
    "cv.languages": "Languages",
    "cv.technical_skills": "Technical Skills",
    "cv.complete": "For a complete CV, please click the download button above or",
    "cv.contact": "contact me",
    "blog.title": "Blog",
    "blog.latest": "Latest Posts",
    "blog.categories": "Categories",
    "blog.tags": "Tags",
    "blog.readmore": "Read More",
    "publications.journal.label": "Journal",
    "publications.conference.label": "Conference",
    "publications.book.label": "Book",
    "publications.field.labor-economics": "Labor Economics",
    "publications.field.agricultural-economics": "Agricultural Economics",
    "publications.field.political-science": "Political Science",
    "publications.1.title": "Does the Increase in Female Workers in the Textile Industry Lead to Empowerment or Increased Female Exploitation?",
    "publications.1.authors": "Mo, W.",
    "publications.1.journal": "Journal of Theory and Practice of Social Science",
    "publications.1.year": "2023",
    "publications.1.type": "journal",
    "publications.1.field": "labor-economics",
    "publications.1.doi": "2790-1513",
    "publications.1.abstract": "This paper examines the impact of increased female participation in the textile industry on empowerment versus exploitation, considering working conditions, wages, career advancement, and societal status.",
    "publications.2.title": "Barriers to Women's Gaining a Role in Grassroots Government: The Case of a Questionnaire Survey of Grassroots Civil Servants in China.",
    "publications.2.authors": "Mo, W.",
    "publications.2.journal": "Studies in Social Science & Humanities",
    "publications.2.year": "2024",
    "publications.2.type": "journal",
    "publications.2.field": "political-science",
    "publications.2.doi": "2709-7862",
    "publications.2.abstract": "This study applied labor economics frameworks to quantify gender disparities in political labor markets, examined institutional inefficiencies through an organizational economics lens, and measured social capital returns using network analysis metrics.",
    "publications.3.title": "Conservation of Indigenous Pig Breeds and Cooperative Development with Small-scale Farmers in Guangdong.",
    "publications.3.authors": "Zhang, H., Mo, W., Liang, J., et al.",
    "publications.3.journal": "Swine Industry",
    "publications.3.year": "2024",
    "publications.3.type": "journal",
    "publications.3.field": "agricultural-economics",
    "publications.3.doi": "4, 15-18",
    "publications.3.abstract": "This research focuses on the conservation of indigenous pig breeds and promoting cooperative development with small-scale farmers in Guangdong.",
    "publications.4.title": "Current status and trends in the pork consumption market.",
    "publications.4.authors": "Zhang, H., Liu, S., Mo, W., & Liu, W.",
    "publications.4.journal": "Swine Industry",
    "publications.4.year": "2024",
    "publications.4.type": "journal",
    "publications.4.field": "agricultural-economics",
    "publications.4.doi": "4, 25-30",
    "publications.4.abstract": "This paper analyzes the current status and future trends in the pork consumption market.",
    "publications.5.title": "Reflections on the construction of a full-industry-chain pig farming conglomerate.",
    "publications.5.authors": "Liu, L., Feng, X., Mo, W., & Zhang, H.",
    "publications.5.journal": "Swine Industry",
    "publications.5.year": "2024",
    "publications.5.type": "journal",
    "publications.5.field": "agricultural-economics",
    "publications.5.doi": "4, 31-35",
    "publications.5.abstract": "This article provides reflections on the construction of a full-industry-chain pig farming conglomerate.",
    "education.1.period": "2021.09-2022.12",
    "education.1.school": "University of Birmingham (England, UK)",
    "education.1.degree": "MA International Political Economy, Social Science (Merit)",
    "education.1.gpa": "GPA: 63%",
    "education.1.courses": "Relevant Modules: International Political Economy, Globalisation & Governance, Global Environmental Governance, Doing Political Research",
    "education.1.paper": "Course Paper: Does the Increase in Female Workers In The Textile Industry Lead To Empowerment Or Exploitation; Is Globalization Good for Women; The Contributions of Environmental NGOs and Business Actors in Global Environmental Governance; etc.",
    "education.2.period": "2019.09-2020.09",
    "education.2.school": "University of Huddersfield (England, UK)",
    "education.2.degree": "BA International Business, Business School (Upper Second Class)",
    "education.2.gpa": "GPA: 68%",
    "education.2.courses": "Relevant Courses: International Business, Strategic Management, Cross-Cultural Studies, Environmental Policy, Business Responsibility and Sustainability, The Psychology of Work & Organisations",
    "education.3.period": "2016.09-2020.06",
    "education.3.school": "Guangzhou Huashang College (Guangdong, China)",
    "education.3.degree": "BBM International Business, School of Economics and Finance",
    "education.3.courses": "Relevant Courses: Econometrics, International Finance, Global Marketing Management, International Trade in Technology and Services",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
